name: 🧪

on:
  push:
    branches:
      - main

jobs:
  check-version:
    name: 🪨
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make HTML index
      run: make html

