name: 🧪

on:
  push:
    branches:
      - main

jobs:
  check-version:
    name: 🪨
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make HTML index
      run: make html
    - name: Make HTML index as a single file
      run: make html-single-file

    - name: Run tests
      run: |
        pip install pytest
        python3 -m pytest test/
