name: 🚀

on:
  push:
    branches:
      - main

jobs:
  check-version:
    name: 🪨
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install PyGitHub
      run: python3 -m pip install PyGitHub
    - name: Check version number and make release if necessary
      run: python .github/scripts/version.py ${{ secrets.GITHUB_TOKEN }}

